config/routes.rb
Rails.application.routes.draw do

  get 'cart/index'

  get 'site/about'

  resources :profiles

  get 'site/about'
  
  get 'site/contact'
  
  get 'site/search'
  
  get 'site/login'
  
  get 'site/register'
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/search' => 'site#search'
  get '/login' => 'site#login'
  post '/login' => 'user#admin_login'
  get '/logout' => 'user#logout'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/register' => 'site#register'

  get '/cart/:id' => 'cart#add'
  

  post '/register' => 'user#register'

  

  resources :returns

  resources :sale_items

  resources :sales

  resources :books

  resources :suppliers
  
  resources :checkout

  devise_for :admins
  devise_for :users
  

  root 'items#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :supplier
  
   def self.search(search)
    where("category LIKE ? OR  title LIKE ? OR author LIKE ?" , "%#{search}%", "%#{search}%", "%#{search}%")
  end
  
#   def self.search(search)
#     where("category LIKE ?",  "%#{search}%")
#   end
  
  
  #  def self.search(search)
  #   where("category LIKE ?", "Crime")
  # end
  
   
  
 
  
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/return.rb
class Return < ActiveRecord::Base
  belongs_to :saleItem
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :user
end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
  belongs_to :book
  belongs_to :sale
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    id = params[:id]
    if session[:cart] then
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end
    
    if cart[id] then
      cart[id] = cart[id] + 1
    else
      cart[id] = 1
    end
    
    redirect_to :action => :index
    
  end
  
  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
    
  end
     
     def index
       if session[:cart] then
         @cart = session[:cart]
       else
         @cart = {}
    end
  end
  
end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
  before_action :set_return, only: [:show, :edit, :update, :destroy]

  # GET /returns
  # GET /returns.json
  def index
    @returns = Return.all
  end

  # GET /returns/1
  # GET /returns/1.json
  def show
  end

  # GET /returns/new
  def new
    @return = Return.new
  end

  # GET /returns/1/edit
  def edit
  end

  # POST /returns
  # POST /returns.json
  def create
    @return = Return.new(return_params)

    respond_to do |format|
      if @return.save
        format.html { redirect_to @return, notice: 'Return was successfully created.' }
        format.json { render :show, status: :created, location: @return }
      else
        format.html { render :new }
        format.json { render json: @return.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /returns/1
  # PATCH/PUT /returns/1.json
  def update
    respond_to do |format|
      if @return.update(return_params)
        format.html { redirect_to @return, notice: 'Return was successfully updated.' }
        format.json { render :show, status: :ok, location: @return }
      else
        format.html { render :edit }
        format.json { render json: @return.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /returns/1
  # DELETE /returns/1.json
  def destroy
    @return.destroy
    respond_to do |format|
      format.html { redirect_to returns_url, notice: 'Return was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_return
      @return = Return.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def return_params
      params.require(:return).permit(:returnDate, :saleItem_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end

  def search
  end

  def login
    
  end

  def register
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def admin_login
    puts params[:user][:email]
    puts params[:user][:password]
    session[:login] = 1
    session[:cart] = nil
    flash[:notice] = "Login Successfull!!"
    redirect_to :controller => :books
    end

    def logout
    session[:login] = nil
    session[:cart] = nil
    flash[:notice] = "You have been successfully logged out!!"
    redirect_to :controller=> :books
    
    end
    
    def register
    puts params[:user][:email]
    puts params[:user][:password]
    session[:login] = 1
    session[:cart] = nil
    flash[:notice] = "Registered Successfully!!"
    redirect_to :controller => :books

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/returns/_form.html.erb
<%= form_for(@return) do |f| %>
  <% if @return.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@return.errors.count, "error") %> prohibited this return from being saved:</h2>

      <ul>
      <% @return.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :returnDate %><br>
    <%= f.date_select :returnDate %>
  </div>
  <div class="field">
    <%= f.label :saleItem_id %><br>
    <%= f.text_field :saleItem_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/returns/edit.html.erb
<h1>Editing Return</h1>

<%= render 'form' %>

<%= link_to 'Show', @return %> |
<%= link_to 'Back', returns_path %>

app/views/returns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Returns</h1>

<table>
  <thead>
    <tr>
      <th>Returndate</th>
      <th>Saleitem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @returns.each do |return| %>
      <tr>
        <td><%= return.returnDate %></td>
        <td><%= return.saleItem %></td>
        <td><%= link_to 'Show', return %></td>
        <td><%= link_to 'Edit', edit_return_path(return) %></td>
        <td><%= link_to 'Destroy', return, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Return', new_return_path %>

app/views/returns/new.html.erb
<h1>New Return</h1>

<%= render 'form' %>

<%= link_to 'Back', returns_path %>

app/views/returns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Returndate:</strong>
  <%= @return.returnDate %>
</p>

<p>
  <strong>Saleitem:</strong>
  <%= @return.saleItem %>
</p>

<%= link_to 'Edit', edit_return_path(@return) %> |
<%= link_to 'Back', returns_path %>