config/routes.rb
Rails.application.routes.draw do

  get 'cart/index'

  get 'site/about'

  resources :profiles

  get 'site/about'
  
  get 'site/contact'
  
  get 'site/search'
  
  get 'site/login'
  
  get 'site/register'
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/search' => 'site#search'
  get '/login' => 'site#login'
  post '/login' => 'user#admin_login'
  get '/logout' => 'user#logout'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/register' => 'site#register'

  get '/cart/:id' => 'cart#add'
  

  post '/register' => 'user#register'

  

  resources :returns

  resources :sale_items

  resources :sales

  resources :books

  resources :suppliers
  
  resources :checkout

  devise_for :admins
  devise_for :users
  

  root 'items#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :supplier
  
   def self.search(search)
    where("category LIKE ? OR  title LIKE ? OR author LIKE ?" , "%#{search}%", "%#{search}%", "%#{search}%")
  end
  
#   def self.search(search)
#     where("category LIKE ?",  "%#{search}%")
#   end
  
  
  #  def self.search(search)
  #   where("category LIKE ?", "Crime")
  # end
  
   
  
 
  
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/return.rb
class Return < ActiveRecord::Base
  belongs_to :saleItem
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :user
end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
  belongs_to :book
  belongs_to :sale
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    id = params[:id]
    if session[:cart] then
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end
    
    if cart[id] then
      cart[id] = cart[id] + 1
    else
      cart[id] = 1
    end
    
    redirect_to :action => :index
    
  end
  
  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
    
  end
     
     def index
       if session[:cart] then
         @cart = session[:cart]
       else
         @cart = {}
    end
  end
  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end

  def search
  end

  def login
    
  end

  def register
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def admin_login
    puts params[:user][:email]
    puts params[:user][:password]
    session[:login] = 1
    session[:cart] = nil
    flash[:notice] = "Login Successfull!!"
    redirect_to :controller => :books
    end

    def logout
    session[:login] = nil
    session[:cart] = nil
    flash[:notice] = "You have been successfully logged out!!"
    redirect_to :controller=> :books
    
    end
    
    def register
    puts params[:user][:email]
    puts params[:user][:password]
    session[:login] = 1
    session[:cart] = nil
    flash[:notice] = "Registered Successfully!!"
    redirect_to :controller => :books

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/index.html.erb
<h1>Shopping Cart</h1>

<% if @cart.empty? %>
<p>Your cart is empty</p>
<% end %>

<% total = 0 %>

<table class="cart">
    <tr>
        <td class="legend"></td>
        <td class="legend">Item</td>
        <td class="legend">Price</td>
        <td class="legend">Quantity</td>
        <td class="legend">Total</td>
    </tr>
    
<% @cart.each do |id,quantity | %>
<% book = Book.find_by_id(id)%>
<tr>
    <td>
        <div class="image">
           
        </div>
    </td>
    <td class="title"><%= link_to  'book.title', book %></td>
    <td class="price"><%= number_to_currency(22) %></td>
    <td class="quantity"><%= quantity %> <br /> </td>
    <td class="price"><%= number_to_currency(quantity * 22, :unit => "£") %></td>
</tr>
    <% total += quantity *22 %>
<% end %>
<tr>
    <td colspan="4">
        <div class="total">Total:</div>
    </td>
    <td>
        <div class="price"><%= number_to_currency(total, :unit => "Eur") %></div>
    </td>
</tr>
</table>
<p>
    <%= link_to 'Continue Shopping', :controller => :books %>
</p>

app/views/site/about.html.erb
<html>
<h1>ABOUT US</h1>
<body>

<p>Thank you for visiting the BookShop.</p>
<br/>
<p>
The BookShop websites was founded in 2017 by National College of Ireland students. The goal of the BookShop is to be a strong Ireland based 
website selling books to a predominantly Irish customer base, both within Ireland but also to the worldwide book lovers diaspora.
</p>
<br/>
<p>
If you love books as much as we do you are on the right website. We sell books from all different categories, from horrific 
horrors to hilarious comedy's. Please feel free to get in touch using our contact us page and one of our representatives will get in touch.
</p>

</body>
</html>

app/views/site/checkout.html.erb
<h1>Site#checkout</h1>
<p>Find me in app/views/site/checkout.html.erb</p>

app/views/site/contact.html.erb
<h1>Contact us!</h1>

<form id="contact_form" action="#"form action="http://formspree.io/x16124103@student.ncirl.ie" method="post">
 <div class="row">
    <label for="email">Your email:</label><br />
  <input type="email" name="_replyto">
  </div>
  <div class="row">
      <label for="message">Message:</label><br />
  <textarea name="body"rows="7" cols="30"></textarea>
  </div>
  <div class="row">
      <label for="message"></label><br />
  <input id="submit_button"input type="submit" value="Submit">
  </div>
</form>

app/views/site/login.html.erb
<h1>Login</h1>

<%= form_for(:user, :html => {class: "form-horizontal", role: "form"}, url: login_path) do |f| %>

<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :email %>
</div>
<div class="col-sm-8">
<%= f.email_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
</div>
</div>

<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :password %>
</div>
<div class="col-sm-8">
<%= f.password_field :password, class: "form-control", autocomplete: "off" %>
</div>
</div>

<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<%= f.submit "Log in", class: 'btn btn-primary btn-lg' %>
</div>
</div>

<% end %>

app/views/site/register.html.erb
<h1>Register</h1>

<%= form_for(:user, :html => {class: "form-horizontal", role: "form"}, url: register_path) do |f| %>

<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :email %>
</div>
<div class="col-sm-8">
<%= f.email_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
</div>
</div>

<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :password %>
</div>
<div class="col-sm-8">
<%= f.password_field :password, class: "form-control", autocomplete: "off" %>
</div>
</div>

<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<%= f.submit "Register", class: 'btn btn-primary btn-lg' %>
</div>
</div>

<% end %>

app/views/site/search.html.erb
<h1>Search For Books</h1>
<p id="notice"><%= notice %></p>

<%=form_tag(books_path, :method => "get" , id: "search.form") do %>
  <%= text_field_tag :search, params[:search],:size=> 30, placeholder: " Search Books By Title or Author"%>
  <%= submit_tag "Search" %>
  <% end %>
  
  
  

  
 