config/routes.rb
Rails.application.routes.draw do

  get 'cart/index'

  get 'site/about'

  resources :profiles

  get 'site/about'
  
  get 'site/contact'
  
  get 'site/search'
  
  get 'site/login'
  
  get 'site/register'
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/search' => 'site#search'
  get '/login' => 'site#login'
  post '/login' => 'user#admin_login'
  get '/logout' => 'user#logout'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/register' => 'site#register'

  get '/cart/:id' => 'cart#add'
  

  post '/register' => 'user#register'

  

  resources :returns

  resources :sale_items

  resources :sales

  resources :books

  resources :suppliers
  
  resources :checkout

  devise_for :admins
  devise_for :users
  

  root 'items#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :supplier
  
   def self.search(search)
    where("category LIKE ? OR  title LIKE ? OR author LIKE ?" , "%#{search}%", "%#{search}%", "%#{search}%")
  end
  
#   def self.search(search)
#     where("category LIKE ?",  "%#{search}%")
#   end
  
  
  #  def self.search(search)
  #   where("category LIKE ?", "Crime")
  # end
  
   
  
 
  
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/return.rb
class Return < ActiveRecord::Base
  belongs_to :saleItem
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :user
end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
  belongs_to :book
  belongs_to :sale
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    id = params[:id]
    if session[:cart] then
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end
    
    if cart[id] then
      cart[id] = cart[id] + 1
    else
      cart[id] = 1
    end
    
    redirect_to :action => :index
    
  end
  
  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
    
  end
     
     def index
       if session[:cart] then
         @cart = session[:cart]
       else
         @cart = {}
    end
  end
  
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:saleTotal, :qtySold, :saleDate, :user_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end

  def search
  end

  def login
    
  end

  def register
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def admin_login
    puts params[:user][:email]
    puts params[:user][:password]
    session[:login] = 1
    session[:cart] = nil
    flash[:notice] = "Login Successfull!!"
    redirect_to :controller => :books
    end

    def logout
    session[:login] = nil
    session[:cart] = nil
    flash[:notice] = "You have been successfully logged out!!"
    redirect_to :controller=> :books
    
    end
    
    def register
    puts params[:user][:email]
    puts params[:user][:password]
    session[:login] = 1
    session[:cart] = nil
    flash[:notice] = "Registered Successfully!!"
    redirect_to :controller => :books

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :saleTotal %><br>
    <%= f.text_field :saleTotal %>
  </div>
  <div class="field">
    <%= f.label :qtySold %><br>
    <%= f.number_field :qtySold %>
  </div>
  <div class="field">
    <%= f.label :saleDate %><br>
    <%= f.date_select :saleDate %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Saletotal</th>
      <th>Qtysold</th>
      <th>Saledate</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.saleTotal %></td>
        <td><%= sale.qtySold %></td>
        <td><%= sale.saleDate %></td>
        <td><%= sale.user %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Saletotal:</strong>
  <%= @sale.saleTotal %>
</p>

<p>
  <strong>Qtysold:</strong>
  <%= @sale.qtySold %>
</p>

<p>
  <strong>Saledate:</strong>
  <%= @sale.saleDate %>
</p>

<p>
  <strong>User:</strong>
  <%= @sale.user %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>